### ISSUE TITLE
[问题反馈]: 一级标题和二级标题异常

### ISSUE THREAD

**Issue by chendeqiang1024** [Mereithhh/vanblog#100]
### 问题描述 | Describe the bug

二级标题也要tab一下吧，现在这个状态没有区分度。

<img width="1209" alt="image" src="https://user-images.githubusercontent.com/93462676/204119803-ce1cffdc-8724-4a69-b3a0-2627a8aa7d7f.png">

### 版本 | Version

v0.43.1

### 部署方式？ | How do you deploy vanblog?

Docker 部署(文档默认)

**Comment by Mereithhh** [comment]
tab 一下具体指？可以给一个样例吗？

**Comment by chendeqiang1024** [comment]
tab就是tab键位。我觉得腾讯云的这个一级标题和二级标题挺好看的，https://cloud.tencent.com/developer/article/1631713
![image](https://user-images.githubusercontent.com/93462676/204412455-19b8dd0f-ebd6-48de-b3d8-7675f1426ada.png)

**Comment by Mereithhh** [comment]
收到

**Comment by Mereithhh** [comment]
给一级标题加了点缩进，但因为目前很多人（包括我）习惯直接用二级标题起手，所以不敢加太多缩进。 我仔细看了你发的腾讯云文档，它的这个一级标题实际上是二级标题，这个人也是从二级标题开始写的。

后面会考虑加一个目录折叠功能，这次先改一版看看吧。

此 issue 就先关了，下次发版就上了。
