### ISSUE TITLE
[优化建议]: 希望添加图片的时候能够加入水印的功能

### ISSUE THREAD

**Issue by snailBoy0305** [Mereithhh/vanblog#106]
### 功能概述 | Describe the feature

 希望添加图片的时候能够加入水印的功能

现在上传的图片没有任何水印，希望下次版本加上图片的水印

最好是水印位置不要固定，随机位置的水印

**Comment by Mereithhh** [comment]
收到，我会尽快做，但需求比较多，所以不能保证很快上。

**Comment by 8ty** [comment]
建议可以使用第三方软件比如picgo或者sharex来实现，因为我感觉这个功能可能对于我来说不太有用😂

**Comment by Mister-Hope** [comment]
I think this is already supported?

**Comment by Mereithhh** [comment]
有了有了，虽然很简陋。后续会增加更多水印相关功能。

**Comment by 6uu1** [comment]
> I think this is already supported?

so may i ask why you speak english here?for practising?

**Comment by Mister-Hope** [comment]
If you are an active developer on GitHub, then you won't ask questions like this. English is my primary choice on GitHub. I understand that this project only have Chinese docs for now, but I am planning to ship an en docs when I have time.

I have several projects which most of the collaborators are Chinese, yet we still communicate with others in English. When you use English, it makes sure that most GitHub visitors can understand what you are talking. Is this clear enough for you?
