### ISSUE TITLE
[问题反馈]: 个别分类无法删除修改

### ISSUE THREAD

**Issue by SmallOrangeGame** [Mereithhh/vanblog#107]
### 问题描述 | Describe the bug

![image](https://user-images.githubusercontent.com/58835407/205475043-e84d66e2-55cd-4f7f-8ca9-0a143e291f23.png)
![image](https://user-images.githubusercontent.com/58835407/205475055-57d02d3b-3dba-4e4d-8c2b-7cb1c6cc33e2.png)

### 复现网址 | Website URL

https://www.xiaojuziya.com/

### 版本 | Version

v.0.43.1

### 部署方式？ | How do you deploy vanblog?

Docker 部署(文档默认)

**Comment by Mereithhh** [comment]
是因为删除用了 DELETE 请求，然后 # 号附带到 url 后面直接被当成哈希忽略掉了。

**Comment by Mereithhh** [comment]
修了一下，等收到更新通知更新一下应该就好了。
