### ISSUE TITLE
[问题反馈]: 修改文章标签BUG

### ISSUE THREAD

**Issue by DingDangDog** [Mereithhh/vanblog#111]
### 问题描述 | Describe the bug

修改标签可以成功，且文章列表也会更新出新的标签，但再次点击【修改信息】弹出的修改框中，仍然是修改前的标签，此时直接点击确定。标签又还原回去了。。。
![GIF 2022-12-12 22-19-12](https://user-images.githubusercontent.com/45959431/207068767-0dbb6b3f-d3a5-43a3-9e2b-bee9f522a354.gif)

### 复现网址 | Website URL

https://oldmoon.top

### 版本 | Version

v0.43.1

### 部署方式？ | How do you deploy vanblog?

Docker 部署(文档默认)

**Comment by DingDangDog** [comment]
应该是表单数据绑定的问题吧

**Comment by Mereithhh** [comment]
收到，我看看

**Comment by Mereithhh** [comment]
修了，等收到更新通知，更新一下就好了。

**Comment by Qinchuan008** [comment]
怎么新增标签呀？

**Comment by dingdangdog** [comment]
> 怎么新增标签呀？

新建/修改文章时，输入要新增的标签，然后选中，保存时即可自动新增。
