### ISSUE TITLE
[问题反馈]: 文章目录标题显示、点击异常

### ISSUE THREAD

**Issue by QinYupan** [Mereithhh/vanblog#112]
### 问题描述 | Describe the bug

右侧导航栏显示有一点问题。且二级标题相同时，点击导航栏的标题2，每次都会跳转到同一个位置
<img width="1155" alt="image" src="https://user-images.githubusercontent.com/27144932/208714650-cc2ca553-d0a9-4bb5-bf9b-cc82775c8b7b.png">

### 版本 | Version

v0.44.0

### 部署方式？ | How do you deploy vanblog?

Docker 部署(文档默认)

**Comment by immengzi** [comment]
@Mereithhh 的确存在此问题。

**Comment by Mereithhh** [comment]
收到

**Comment by Mereithhh** [comment]
`v0.45.0` 版本已修复，先关啦，有问题再开～
