### ISSUE TITLE
[问题反馈]: 目录丢失

### ISSUE THREAD

**Issue by sundongyu** [Mereithhh/vanblog#117]
### 问题描述 | Describe the bug

经过测试，如果最后一个二级标题下只有一个代码块，该标题将消失于目录中

如下，标题三将不会显示在目录中

## 标题3
``` txt
qwer
```

### 复现网址 | Website URL

https://wetf.top/post/66

### 版本 | Version

v0.44.0

### 部署方式？ | How do you deploy vanblog?

其他方式

**Comment by Mereithhh** [comment]
好的，我看看修一下

**Comment by Mereithhh** [comment]
`v0.45.0` 中已修复
