### ISSUE TITLE
[问题反馈]: mongo数据库初始化用户密码和不初始化用户密码均不能连接

### ISSUE THREAD

**Issue by Gavincent1** [Mereithhh/vanblog#120]
### 问题描述 | Describe the bug

![image](https://user-images.githubusercontent.com/34804116/212553932-2b5722f8-e701-4df4-8b07-494255f69ed9.png)
![image](https://user-images.githubusercontent.com/34804116/212553990-4cdd1a0b-6924-4ff1-864b-c10755e9ac84.png)
mongo数据库初始化用户密码和不初始化用户密码均不能连接，不清楚是什么问题？

### 版本 | Version

0.44.0

### 部署方式？ | How do you deploy vanblog?

Docker 部署(文档默认)

**Comment by Mereithhh** [comment]
有个办法，你可以试试。 你把 mongoDB 映射到本地端口，vanblog 通过群晖 IP + 映射的端口访问试试看？

**Comment by Mereithhh** [comment]
先关啦，有问题再提
