### ISSUE TITLE
[优化建议]: 一键安装脚本可以有优先docker compose v2，其次docker-compose

### ISSUE THREAD

**Issue by RayWangQvQ** [Mereithhh/vanblog#122]
### 功能概述 | Describe the feature

docker很久之前已将`docker compose`集成到CLI里了，被称为`docker compose v2`，且v2是未来的方向。只要装了docker，就是可以直接执行docker compose的。

所以出来非常老版本的docker需要单独安装的`docker-compose`插件外，v1并不是必须的，但当前使用一键安装脚本会进行自动安装docker-compose插件。

参考：

[https://docs.docker.com/compose/compose-v2/](https://docs.docker.com/compose/compose-v2/)

[https://www.howtogeek.com/devops/how-to-upgrade-to-docker-compose-v2/](https://www.howtogeek.com/devops/how-to-upgrade-to-docker-compose-v2/)

作者是否觉得，可以优化下脚本逻辑，思路有两个：

1. 将`docker compose`单独拎出一个函数，函数里会先判断是否支持v2，并优先使用v2，如果不支持再去安装插件并使用`docker-compose v1`
2. 不单独拎出一个函数，而是precheck环境时，如果发现已经支持v2，就创建一个linux别名兼容docker-compose（`echo 'alias docker-compose="docker compose"' >> ~/.bashrc`）

P.S.我可以贡献PR以帮忙分摊工作量（如果需要的话）

**Comment by Mereithhh** [comment]
收到，这两天工作不那么忙了，我抽空搞一搞

**Comment by Mereithhh** [comment]
加上了，无脑 v2，现在回头看这个 issue 才发现忘了做老版本兼容了。。。 先这样吧，回头有人提了我再加上老 compose 兼容（偷懒）。

您要是有空帮我加上的话我灰常欢迎！
