### ISSUE TITLE
[问题反馈]: google 的analytics和search-console 出错

### ISSUE THREAD

**Issue by 8ty** [Mereithhh/vanblog#129]
## analytics已在后台填写完毕
![image](https://user-images.githubusercontent.com/92656899/213192216-d9109310-6b34-49c5-8a74-45e9e9537ae3.png)
![image](https://user-images.githubusercontent.com/92656899/213192265-8769fb7d-5018-4777-ba24-fd587f65b6b7.png)
![image](https://user-images.githubusercontent.com/92656899/213192371-c9ff5aeb-d4bc-45cd-8913-c0f7dd4c16ed.png)

## search-console 无法读取此站点地图
![image](https://user-images.githubusercontent.com/92656899/213191696-126e1771-9893-4522-a979-71905fc62786.png)

### 版本 | Version

0.44

### 部署方式？ | How do you deploy vanblog?

Docker 部署(文档默认)

**Comment by 8ty** [comment]
analytics 已解决，
但是站点地图仍然无法抓取

**Comment by Mereithhh** [comment]
收到

**Comment by 8ty** [comment]
> 收到

希望尽快解决站点地图问题，不然谷歌都不收录了😂

**Comment by Mereithhh** [comment]
你是怎么在 search-console 校验站点的，dns 吗？

**Comment by 8ty** [comment]
> 你是怎么在 search-console 校验站点的，dns 吗？

是的，而且提交rss链接可以，是的sitemap就不行

**Comment by Mereithhh** [comment]
我用支持自定义 head 标签的测试版本验证通过后，提交了站点地图，是 ok 的。
<img width="1014" alt="image" src="https://user-images.githubusercontent.com/22872368/216219189-1fbc016d-02d7-47b2-9e3c-26c9b2dacb59.png">
是不是你的站点地图有一些特殊的字符无法识别？ 或者因为是通过 dns 校验导致的。

**Comment by 8ty** [comment]
站点地图里并无不妥啊，dns校验如果会阻止谷歌爬虫的话，为什么rss又可以正常爬取呢？😂有点迷

**Comment by Mereithhh** [comment]
你的 url 输入的正确吗？ 是不是因为你用了 cf 之类的东西。 直接访问 sitemap.xml 可以吗

**Comment by 8ty** [comment]
> 你的 url 输入的正确吗？ 是不是因为你用了 cf 之类的东西。 直接访问 sitemap.xml 可以吗

url 输入正确，从输入的url是可以正常访问站点地图的，我试着将cf去掉，但是也不行，直接访问 sitemap.xml是可以的

**Comment by Mereithhh** [comment]
。。。那就离谱了

**Comment by 8ty** [comment]
在网址最后加上/后成功了，好离谱。。。。

**Comment by guojingwen** [comment]
我也是无法抓取，  cf 是啥意思啊

**Comment by guojingwen** [comment]
> 在网址最后加上/后成功了，好离谱。。。。

加 /  解决了
