### ISSUE TITLE
[问题反馈]: 进入后台一直转圈，但是进不出去

### ISSUE THREAD

**Issue by 8ty** [Mereithhh/vanblog#134]
### 问题描述 | Describe the bug

控制台的报错
Uncaught SyntaxError: Invalid or unexpected token (at umi.8edeb3bb.js:189:13991)

### 版本 | Version

0.44

### 部署方式？ | How do you deploy vanblog?

Docker 部署(文档默认)

**Comment by RayWangQvQ** [comment]
同遇到过一次，你是不是管理后台改过token的有效时间？

**Comment by 8ty** [comment]
> 同遇到过一次，你是不是管理后台改过token的有效时间？

token的有效时间?貌似没有改过，可以说说具体在那个地方吗

**Comment by Mereithhh** [comment]
token 有效时间在后台设置中，你检查一下  vanblog 本身的日志看看有没有异常？  或者尝试重启 vanblog 或者换个设备/浏览器试试？

**Comment by 8ty** [comment]
![Uploading image.png…]()
是这个吗？通过ip进去，并没有改过。vanblog的日志也没有什么异常，重启重启 vanblog 或者换个设备/浏览器甚至是换个网络也无效

**Comment by 8ty** [comment]
解决了，在cloudflare仪表盘清除全部缓存后可以了，不知道要怎么在cf里设置缓存才正确

**Comment by 8ty** [comment]
然后后面在控制台调试的时候会出现这个
![image](https://user-images.githubusercontent.com/92656899/215043478-23eb45df-3a6d-4b5d-bcf2-1c6c29fb506e.png)
就会正常一次，下次一刷新又会继续转圈

**Comment by 8ty** [comment]
已解决，是cf的自动压缩js的锅

**Comment by Mereithhh** [comment]
妙。

**Comment by PAN-jingcheng** [comment]
我也遇到了，请问具体是怎么解决的呀？

**Comment by Mereithhh** [comment]
一般几种情况：
- 你开了广告拦截的插件，关掉试试。
- 你没有清理浏览器缓存，清理一下或者换个浏览器试试
- 和上面的一样，你如果套了 cf，关了自动压缩代码。或者直接通过 ip + 端口访问试试

**Comment by Mereithhh** [comment]
@PAN-jingcheng

**Comment by PAN-jingcheng** [comment]
好的，谢谢
