### ISSUE TITLE
分类数目显示为0 

### ISSUE THREAD

**Issue by Southyang** [Mereithhh/vanblog#146]
### 问题描述 | Describe the bug

- 在分类界面里可以正常显示已有分类，但数目为0；
![%)K{V7}( ~EWX(~)%YLXXF4](https://user-images.githubusercontent.com/60416370/216983629-6b1dbcb4-2d13-4760-9f74-05e7a2596890.png)

- 首页显示里也是0
![image](https://user-images.githubusercontent.com/60416370/216983797-e89e80d8-05e4-4e59-bf2f-17705b3fb999.png)

### 版本 | Version

0.45.3

### 部署方式？ | How do you deploy vanblog?

Docker 部署(文档默认)

**Comment by Mereithhh** [comment]
收到，我看看

**Comment by Mereithhh** [comment]
已修复，一会发一版。。。

**Comment by Southyang** [comment]
收到！感谢大佬！
