### ISSUE TITLE
[问题反馈]: 更新到0.45后首页全部消失

### ISSUE THREAD

**Issue by 8ty** [Mereithhh/vanblog#149]
### 问题描述 | Describe the bug

![](https://i0.wp.com/telegra.ph/file/d60830780b377299967b2.png)
手动触发也不行

### 版本 | Version

0.45

### 部署方式？ | How do you deploy vanblog?

Docker 部署(文档默认)

**Comment by RayWangQvQ** [comment]
+1
后台数据都在，前台文章、分类、标签全没了。

从后台文章列表点查看文章，返回500

**Comment by RayWangQvQ** [comment]
经验证，`v0.45.4`有同样问题，回退到`v0.45.3`恢复正常

**Comment by Mereithhh** [comment]
我发现了…… 我正在紧急发版，抱歉

**Comment by Mereithhh** [comment]
修好了，更新一下就好了。
