### ISSUE TITLE
[问题反馈]: 后台文章管理，顶置排序不好用

### ISSUE THREAD

**Issue by DingDangDog** [Mereithhh/vanblog#156]
### 问题描述 | Describe the bug

如下图，排序有问题，不知道是否因为历史设置过顶置数字，后来改回0了，但还是按照历史设置数字的排序？

![image](https://user-images.githubusercontent.com/45959431/218366691-732c93dd-ccb2-48fe-98df-d6075285d0bd.png)

### 版本 | Version

v0.45.3

### 部署方式？ | How do you deploy vanblog?

Docker 部署(文档默认)

**Comment by Mereithhh** [comment]
收到

**Comment by Mereithhh** [comment]
我没能复现这个问题，可以在群里私聊我或者加我微信吗？我自己查查

**Comment by DingDangDog** [comment]
清了一下缓存，就好了。。。缓存好坑啊。。。我关了issues吧。。。

**Comment by Mereithhh** [comment]
缓存指的是浏览器缓存吗？

**Comment by DingDangDog** [comment]
> 缓存指的是浏览器缓存吗？

是的，清理浏览器缓存后，重新登录后台就好了。。。
