### ISSUE TITLE
[问题反馈]: 在文章底部切换上下篇时发生错误

### ISSUE THREAD

**Issue by 6uu1** [Mereithhh/vanblog#161]
### 问题描述 | Describe the bug

切换的时候是只有标题变了，文章内容还是原来文章的内容，网址也变了。看了一下，好像demo里也有这个问题

### 复现网址 | Website URL

https://696988.xyz/

### 版本 | Version

0.45.6

### 部署方式？ | How do you deploy vanblog?

Docker 部署(文档默认)

**Comment by 6uu1** [comment]
就像这样（demo里的）
![image](https://user-images.githubusercontent.com/122669698/220600594-966a4c8b-cb55-415b-ab2d-910cb686b810.png)

**Comment by Mereithhh** [comment]
好的

**Comment by Mereithhh** [comment]
定位问题了，是因为之前修另一个问题导致的连带效应，已修复 `v0.45.7` ，正在发布，收到更新提示之后更新一下就好了。

很抱歉带来不便，我尽量早点引入自动化测试方案……

**Comment by 6uu1** [comment]
> 



> 定位问题了，是因为之前修另一个问题导致的连带效应，已修复 `v0.45.7` ，正在发布，收到更新提示之后更新一下就好了。
> 
> 很抱歉带来不便，我尽量早点引入自动化测试方案……

作者大大棒棒的！

**Comment by Mereithhh** [comment]
`v0.45.7` 因为 github 构建缓存，发版有点问题，改成发布为 `v0.46.0` 了
