### ISSUE TITLE
[问题反馈]: 文章刷新页面后代码块内容出现重影

### ISSUE THREAD

**Issue by JiangJunChengGitHub** [Mereithhh/vanblog#162]
### 问题描述 | Describe the bug

从主页点击进入文章页面以后，代码块显示无问题。
在文章页面刷新页面，代码块出现重影效果。
可以到我提供的网址下，点击含有代码块的文章，刷新页面，即可复现。
部署方式：脚本部署

### 复现网址 | Website URL

https://www.realmidc.net/

### 版本 | Version

v0.45.6

### 部署方式？ | How do you deploy vanblog?

其他方式

**Comment by Mereithhh** [comment]
我没能复现，你用的是啥系统+啥浏览器？  pc 端还是移动端？

**Comment by JiangJunChengGitHub** [comment]
> 我没能复现，你用的是啥系统+啥浏览器？ pc 端还是移动端？
您好，感谢回复。

MacOs + Chrome  PC端

我让我朋友也看过了，他是windows系统，问题也存在，您访问的我的链接没有这个问题吗？

**Comment by Mereithhh** [comment]
我不能稳定复现，我尝试修了一版本，部署到测试环境再试试看

**Comment by Mereithhh** [comment]
可能和我的主题切换逻辑或者和我的代码块高亮方案有关，我逐一排查
