### ISSUE TITLE
[Bug]: CLS in navbar

### ISSUE THREAD

**Issue by Mister-Hope** [Mereithhh/vanblog#171]
### 问题描述 | Describe the bug

![image](https://user-images.githubusercontent.com/33315834/221765537-4f944809-5bd9-4bfc-9335-fe8c51d03706.png)

There is a greate CLS here when loading pages, this appears both mobile and desktop

**Comment by Mereithhh** [comment]
Thanks, I was too lazy to fix it. Now I'm motivated to fix it

**Comment by Mereithhh** [comment]
fiexed.
