### ISSUE TITLE
[Bug]: PhotoView issue

### ISSUE THREAD

**Issue by Mister-Hope** [Mereithhh/vanblog#172]
### 问题描述 | Describe the bug

Click here in https://blog-demo.mereith.com/post/28

![image](https://user-images.githubusercontent.com/33315834/221766011-27f10f57-713e-4499-9c72-6083a40bd803.png)

You will trigger an preview panel, and it's definitely not expected.

Also the hidden donate image is found as page images.

![image](https://user-images.githubusercontent.com/33315834/221766246-60019d32-0b9b-4a77-8c35-0ba255d309c7.png)

You may need to update photoview selector and limits it to main content of page。

## more

Support an extra attribute which allows not collecting an image could be better.

E.g.: vuepress-plugin-photo-swipe and vuepress-plugin-lightgallery both support `no-index` on image (e.g.: `<img src="httpsa://example.com/image.png" no-index />`) by setting selector to `.theme-default-content :not(a) > img:not(no-index)`

**Comment by Mereithhh** [comment]
fixed
