### ISSUE TITLE
[Enhancement] TOC Height

### ISSUE THREAD

**Issue by Mister-Hope** [Mereithhh/vanblog#176]
### 功能概述 | Describe the feature

I think the max-height for toc is a bit small.

![image](https://user-images.githubusercontent.com/33315834/221773454-87f85518-3155-462d-add0-8071ab391371.png)

It leaves a large white space on the right side.

**Comment by Mereithhh** [comment]
You are right :)

**Comment by Mister-Hope** [comment]
Oh just found https://github.com/Mereithhh/vanblog/issues/153, closing as dumplicate
