### ISSUE TITLE
Unused method

### ISSUE THREAD

**Issue by Mister-Hope** [Mereithhh/vanblog#210]
https://github.com/Mereithhh/vanblog/blob/f28525bd8d8055612c84dcb93c782183aa64a15b/packages/website/api/addViewer.ts#L30

https://github.com/Mereithhh/vanblog/blob/8ce03e7dcc652cd7951ade582317ead8a80ea76d/packages/website/api/search.ts#L12

These functions are used no where

**Comment by Mereithhh** [comment]
just delete, done.
