### ISSUE TITLE
[问题反馈]: 占用硬盘空间过多

### ISSUE THREAD

**Issue by 6uu1** [Mereithhh/vanblog#249]
### 问题描述 | Describe the bug

好像用着用着就占用很多的硬盘空间

### 版本 | Version

0.47开始

### 部署方式？ | How do you deploy vanblog?

Docker 部署(文档默认)

**Comment by Mereithhh** [comment]
目前迁移到了 `pnpm` 这个问题应该能得到改善，如果真的是因为之前 `yarn` 导致的话。我会再 check 一下的

**Comment by 6uu1** [comment]
> 目前迁移到了 `pnpm` 这个问题应该能得到改善，如果真的是因为之前 `yarn` 导致的话。我会再检查一下的

好的，具体的内容我发在群里了，还请作者能去帮我看看

**Comment by Mereithhh** [comment]
![ce2edfc8f8e2175f514b0aa690a32ac0](https://user-images.githubusercontent.com/22872368/224462939-9e8980ff-ec9e-4917-82d2-f97ae290476c.png)
经过排查是因为更新后，没删除老镜像，老镜像比较多，占用空间就大了。

（这个是解压后的空间，打包体积我也会陆续优化的……）

后续我会在脚本和文档里加上这个步骤的。

删除无用镜像命令 `docker image prune`
