### ISSUE TITLE
[问题反馈]: 130.162.x.x,不能正常链接

### ISSUE THREAD

**Issue by dike3120** [Mereithhh/vanblog#258]
### 问题描述 | Describe the bug

这个IP段不能下载一键脚本，而甲骨文韩国别的IP段都可以下载并安装vanblog，别的已经测试过了。

### 版本 | Version

0.49

### 部署方式？ | How do you deploy vanblog?

Docker 部署(文档默认)

**Comment by dike3120** [comment]
十分感谢，我把脚本文件上传到服务器，执行脚本后，当进行到下载compose文件的时候，也下载不了，不知道啥情况。

**Comment by dike3120** [comment]
好的，我试试，给大佬反馈结果

**Comment by dike3120** [comment]
还是不行，这是流程。
Linux debian 5.10.0-21-arm64 #1 SMP Debian 5.10.162-1 (2023-01-21) aarch64

The programs included with the Debian GNU/Linux system are free software;
the exact distribution terms for each program are described in the
individual files in /usr/share/doc/*/copyright.

Debian GNU/Linux comes with ABSOLUTELY NO WARRANTY, to the extent
permitted by applicable law.
Last login: Tue Mar 21 06:21:17 2023 from 146.56.184.192
root@debian:~# curl -L https://vanblog.mereith.com/vanblog.sh -o vanblog.sh && chmod +x vanblog.sh && ./vanblog.sh
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 12374  100 12374    0     0  26216      0 --:--:-- --:--:-- --:--:-- 26160

    VanBlog 管理脚本 v0.1.4
    --- https://github.com/mereithhh/van-blog ---
    1.  安装 VanBlog
    2.  修改配置
    3.  启动服务
    4.  停止服务
    5.  重启服务
    6.  更新
    7.  查看日志
    8.  卸载
    ————————————————-
    0.  退出脚本
    

请输入选择 [0-8]: 1
> 安装 VanBlog
正在安装 Docker
 Synchronizing state of docker.service with SysV service script with /lib/systemd/systemd-sysv-install.
Executing: /lib/systemd/systemd-sysv-install enable docker
Docker 安装成功
正在安装 Docker Compose
下载脚本失败，请检查本机能否连接 dn-dao-github-mirror.daocloud.io
root@debian:~# curl -L https://vanblog.mereith.com/vanblog.sh -o vanblog.sh && chmod +x vanblog.sh && ./vanblog.sh
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 12374  100 12374    0     0  33263      0 --:--:-- --:--:-- --:--:-- 33263

    VanBlog 管理脚本 v0.1.4
    --- https://github.com/mereithhh/van-blog ---
    1.  安装 VanBlog
    2.  修改配置
    3.  启动服务
    4.  停止服务
    5.  重启服务
    6.  更新
    7.  查看日志
    8.  卸载
    ————————————————-
    0.  退出脚本
    

请输入选择 [0-8]: 1
> 安装 VanBlog
您可能已经安装过 VanBlog，重复安装可能会引发问题，请注意备份。
是否退出安装? [Y/n] y
退出安装
root@debian:~# curl -L https://vanblog.mereith.com/vanblog.sh -o vanblog.sh && chmod +x vanblog.sh && ./vanblog.sh
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 12374  100 12374    0     0  27255      0 --:--:-- --:--:-- --:--:-- 27255

    VanBlog 管理脚本 v0.1.4
    --- https://github.com/mereithhh/van-blog ---
    1.  安装 VanBlog
    2.  修改配置
    3.  启动服务
    4.  停止服务
    5.  重启服务
    6.  更新
    7.  查看日志
    8.  卸载
    ————————————————-
    0.  退出脚本
    

请输入选择 [0-8]: 8
> 卸载 VanBlog，所有数据将都被删除
是否退出卸载? [Y/n] n
继续卸载
./vanblog.sh: line 337: /usr/local/bin/docker-compose: Permission denied
ls: cannot access '/var/vanblog': No such file or directory

* 按回车返回主菜单 *

    VanBlog 管理脚本 v0.1.4
    --- https://github.com/mereithhh/van-blog ---
    1.  安装 VanBlog
    2.  修改配置
    3.  启动服务
    4.  停止服务
    5.  重启服务
    6.  更新
    7.  查看日志
    8.  卸载
    ————————————————-
    0.  退出脚本
    

请输入选择 [0-8]: 1
> 安装 VanBlog
> 修改配置
正在下载编排文件
请输入您的邮箱：dike3120@gmail.com
请输入 http 端口（默认为 80）：
请输入 https 端口（默认为 443）：
配置 修改成功，请稍等重启生效
> 重启服务
./vanblog.sh: line 248: /usr/local/bin/docker-compose: Permission denied
./vanblog.sh: line 249: /usr/local/bin/docker-compose: Permission denied
重启失败，可能是因为启动时间超过了两秒，请稍后查看日志信息

* 按回车返回主菜单 *

    VanBlog 管理脚本 v0.1.4
    --- https://github.com/mereithhh/van-blog ---
    1.  安装 VanBlog
    2.  修改配置
    3.  启动服务
    4.  停止服务
    5.  重启服务
    6.  更新
    7.  查看日志
    8.  卸载
    ————————————————-
    0.  退出脚本
    

请输入选择 [0-8]: 8
> 卸载 VanBlog，所有数据将都被删除
是否退出卸载? [Y/n] n
继续卸载
./vanblog.sh: line 337: /usr/local/bin/docker-compose: Permission denied
ls: cannot access '/var/vanblog': No such file or directory

* 按回车返回主菜单 *

    VanBlog 管理脚本 v0.1.4
    --- https://github.com/mereithhh/van-blog ---
    1.  安装 VanBlog
    2.  修改配置
    3.  启动服务
    4.  停止服务
    5.  重启服务
    6.  更新
    7.  查看日志
    8.  卸载
    ————————————————-
    0.  退出脚本
    

请输入选择 [0-8]: 1
> 安装 VanBlog
> 修改配置
正在下载编排文件
请输入您的邮箱：dike3120@gamil.com
请输入 http 端口（默认为 80）：
请输入 https 端口（默认为 443）：
配置 修改成功，请稍等重启生效
> 重启服务
./vanblog.sh: line 248: /usr/local/bin/docker-compose: Permission denied
./vanblog.sh: line 249: /usr/local/bin/docker-compose: Permission denied
重启失败，可能是因为启动时间超过了两秒，请稍后查看日志信息

* 按回车返回主菜单 *

    VanBlog 管理脚本 v0.1.4
    --- https://github.com/mereithhh/van-blog ---
    1.  安装 VanBlog
    2.  修改配置
    3.  启动服务
    4.  停止服务
    5.  重启服务
    6.  更新
    7.  查看日志
    8.  卸载
    ————————————————-
    0.  退出脚本
    

请输入选择 [0-8]: 7
> 获取日志
./vanblog.sh: line 312: /usr/local/bin/docker-compose: Permission denied

* 按回车返回主菜单 *

    VanBlog 管理脚本 v0.1.4
    --- https://github.com/mereithhh/van-blog ---
    1.  安装 VanBlog
    2.  修改配置
    3.  启动服务
    4.  停止服务
    5.  重启服务
    6.  更新
    7.  查看日志
    8.  卸载
    ————————————————-
    0.  退出脚本
    

请输入选择 [0-8]: 7
> 获取日志
./vanblog.sh: line 312: /usr/local/bin/docker-compose: Permission denied

* 按回车返回主菜单 *

    VanBlog 管理脚本 v0.1.4
    --- https://github.com/mereithhh/van-blog ---
    1.  安装 VanBlog
    2.  修改配置
    3.  启动服务
    4.  停止服务
    5.  重启服务
    6.  更新
    7.  查看日志
    8.  卸载
    ————————————————-
    0.  退出脚本
    

请输入选择 [0-8]:

**Comment by Mereithhh** [comment]
了解了，我明天看一下

**Comment by Mereithhh** [comment]
感谢支持！

看起来有一些权限问题，你使用的是 root 用户吗？如果不是可以切换到 root 用户试试看。

另外在使用脚本之前，可以先运行一下下面的命令，清空之前脚本的缓存目录和安装的 docker-compose
```bash
rm -rf /var/vanblog
rm -rf  /usr/local/bin/docker-compose
```

如果还是不行，明天你加我微信吧，我帮你看看，联系方式我博客里面有。

**Comment by Mereithhh** [comment]
已处理，是因为机器网络问题，导致无法安装 docker 和 docker-compose 导致的，后续会优化一件脚本区分国内和国外的。
