### ISSUE TITLE
[问题反馈]: 设置当前浏览器不计入访问统计引起bug

### ISSUE THREAD

**Issue by dingdangdog** [Mereithhh/vanblog#261]
### 问题描述 | Describe the bug

**bug出现原因**
- 使用`window.localStorage.setItem("noViewer", true);`设置当前浏览器访问不计入访问统计

**bug现象**
1. 使用后，网站底部的访客数和访问数统计数字都显示为0了。
2. 使用后，当前浏览器访问某个文章时，虽然没有被真实记录进数据库，但当次进入文章被计算进了页面显示值。比如首页看到某个文章访问次数是3，进入文章详情页面后，文章被访问次数应该还是3（因为我忽略当前浏览器统计了），但实际上显示的访问次数是4，回到首页刷新，该文章访问次数仍然是3。

该bug在前几个版本一直存在，我看0.50的更新日志里也没有说明修复。

### 复现网址 | Website URL

https://oldmoon.top

### 版本 | Version

v0.49.0

### 部署方式？ | How do you deploy vanblog?

Docker 部署(文档默认)

**Comment by Mereithhh** [comment]
收到，我看看修修，主要是没人提，我想着没人用就没管这块233

**Comment by Mereithhh** [comment]
修了修了。这次发版一起上了
