### ISSUE TITLE
[问题反馈]: 图片放大被覆盖

### ISSUE THREAD

**Issue by CatsAndMice** [Mereithhh/vanblog#265]
### 问题描述 | Describe the bug

博客文章内的图片放大后空白
<img width="1284" alt="image" src="https://user-images.githubusercontent.com/58327088/227687896-ae798844-ee4f-4e50-8d9e-f5c0a70ee19d.png">
原因在于：图片放大创建了多个dom
<img width="1284" alt="image" src="https://user-images.githubusercontent.com/58327088/227687896-ae798844-ee4f-4e50-8d9e-f5c0a70ee19d.png">

### 复现网址 | Website URL

https://www.linglan01.cn/post/15

### 版本 | Version

v0.51.0

### 部署方式？ | How do you deploy vanblog?

Docker 部署(文档默认)

**Comment by Mereithhh** [comment]
收到，之前修markdown换了个图片组件，没注意这块。。

**Comment by Mereithhh** [comment]
新版本中已经好了
