### ISSUE TITLE
[问题反馈]: HTTPS无法开启， Caddy 好像没有自动申请证书

### ISSUE THREAD

**Issue by happyhrw** [Mereithhh/vanblog#273]
### 问题描述 | Describe the bug

![image](https://user-images.githubusercontent.com/100116732/229261688-d2b6e678-f8b1-450d-9df3-5da628fb51d7.png)

### 版本 | Version

V0.51.1

### 部署方式？ | How do you deploy vanblog?

Docker 部署(文档默认)

**Comment by Mereithhh** [comment]
现在的 https 跳转有点问题，你手动在浏览器输入 https 的地址试试看

**Comment by happyhrw** [comment]
> 现在的 https 跳转有点问题，你手动在浏览器输入 https 的地址试试看

我试过了，不可以

**Comment by Mereithhh** [comment]
好的，我会尽快处理

**Comment by Mereithhh** [comment]
已修复，将在下次发版时修复。届时可以关注一下更新提醒

具体 https 自动签发条件请参考文档： https://vanblog.mereith.com/advanced/https.html
