### ISSUE TITLE
[问题反馈]: 自定义s3和webp这两个插件，安装成功，但是写草稿的时候，上传图片报错了

### ISSUE THREAD

**Issue by lihuacai168** [Mereithhh/vanblog#276]
### 问题描述 | Describe the bug

自定义s3和webp这两个插件，安装成功  
但是写草稿的时候，上传图片报错了
![image](https://user-images.githubusercontent.com/11568297/230764539-87c4ff1d-1050-41cf-8a4c-38ad0a740649.png)
![image](https://user-images.githubusercontent.com/11568297/230764550-f3019036-78ca-46c5-bd35-0a567ba3265f.png)

失败后，把webp这款插件移除后
<img width="334" alt="image" src="https://user-images.githubusercontent.com/11568297/230764727-b9ca4a54-6401-4af2-9106-5626a92fbb6e.png">
点击提交
然后在草稿粘贴图片，还是一样的报错

### 版本 | Version

v0.51.1

### 部署方式？ | How do you deploy vanblog?

Docker 部署(文档默认)

**Comment by lihuacai168** [comment]
把webp插件设置为false，提交  
粘贴图片，还是会报错
<img width="352" alt="image" src="https://user-images.githubusercontent.com/11568297/230764871-c8646e1e-fe34-4c0b-ab11-7777c95bcfe5.png">
<img width="1299" alt="image" src="https://user-images.githubusercontent.com/11568297/230764899-41315e89-e28b-4e4a-adea-a4196a882bd4.png">

**Comment by Mereithhh** [comment]
重启一遍容器试试？ 我搭一个环境排查一下

**Comment by lihuacai168** [comment]
vanblog容器重启过了，问题还存在

**Comment by Mereithhh** [comment]
排查了一下，是因为容器里用的 apline 版本的 node 容器，缺少一些依赖导致的。

我在考虑直接集成 webp 转换到 vanblog 本身了，增加一个是否使用 webp 压缩图片的选项，这样本地图床也可以用。

**Comment by lihuacai168** [comment]
直接集成，这是一个好主意，设置为默认功能

**Comment by Mereithhh** [comment]
默认开启好还是关闭好呢？ 直接默认开启会不会疑惑到现有用户？

**Comment by Mereithhh** [comment]
默认开启吧。这样也许好一点

**Comment by lihuacai168** [comment]
> 

不会的呀，新版升级时，加个说明就好了

**Comment by Mereithhh** [comment]
现在已增加自动压缩功能。
