### ISSUE TITLE
[优化建议]: 关于文章中图片URL的优化

### ISSUE THREAD

**Issue by cautms** [Mereithhh/vanblog#303]
### 功能概述 | Describe the feature

问题描述：我在内网部署了vanblog并映射到外网。但是在使用内网地址访问并新建文章时，文章图片的url为：192.168.1.190:3004/img/xx.jpg（举例）；使用外网访问并新建文章时，文章图片url为：blog.xxx.com/img/xxx.jpg。这样会导致在使用不同的地址访问时，非本次访问地址所创建的文章图片内容无法显示。

优化建议：希望能对本地存储的图片路径进行调整。以下是一个参考案例（mrdoc）
![图片](https://github.com/Mereithhh/vanblog/assets/40131065/12c1f833-2a29-4039-854d-16f15e51bdb1)

**Comment by Mereithhh** [comment]
好问题，我修一下

**Comment by Mereithhh** [comment]
改为了： 当时用本地图床时，默认复制和插入到文章中的 markdown 链接，将只包含相对路径，复制 url 链接时不受影响。

**Comment by qulishen** [comment]
这样改也不是完全方便！能不能改成自定义呀，如果我需要将文章同时发布到其他平台，每次都要手动加上外链头！

**Comment by qulishen** [comment]
而且在图片管理，用相对路径的话，看引用文章也看不到
