### ISSUE TITLE
[优化建议]: 

### ISSUE THREAD

**Issue by HotelEnglish** [Mereithhh/vanblog#314]
### 功能概述 | Describe the feature

非常简洁漂亮的博客，打算给我儿子整一个，我试着在Vercel安装程序，没想到居然成功了，但是登录的时候提示“FailED to Fetch”找了整个互联网都没有找到默认的管理员用户和密码!!如果大佬能搞添加一些环境变量，直接在Vercel上通过环境变量设置也好啊！有没有大佬指导一下如何设置管理员账号和密码？感激不尽！

**Comment by Mereithhh** [comment]
没有默认的管理员和密码，按照文档安装会有初始化页面提示你设置密码。 Vercel 不建议，因为默认提供的配置比较低，而且数据没有持久化，容易丢图床和一些数据。 看样子 Vercel 默认情况下是不能用的

**Comment by Mereithhh** [comment]
正常部署会有这个页面的：
![image](https://github.com/Mereithhh/vanblog/assets/22872368/79ac6f9f-c25e-4abe-a49a-b0335edc1de2)

**Comment by Mereithhh** [comment]
解决了吗？ 我先 close 了，有问题再提
