### ISSUE TITLE
[优化建议]: 建议增加一个命令行控制导出数据的方法

### ISSUE THREAD

**Issue by heyi755** [Mereithhh/vanblog#318]
### 功能概述 | Describe the feature

因为我上次不知道怎么把界面整崩溃打不开之后只能重新安装然后数据就都没了

**Comment by Mereithhh** [comment]
收到，合理的需求

**Comment by Mereithhh** [comment]
已添加，晚一会重新获取一遍一键脚本，里面会有导入导出数据的选项了。
