### ISSUE TITLE
[问题反馈]: http 和 https 拉回的文章列表不一致

### ISSUE THREAD

**Issue by lizhiqpxv** [Mereithhh/vanblog#326]
### 问题描述 | Describe the bug

文章有66个，用http访问没有问题是66个；但是反向代理的https 访问只有64个，后面两个是改https之后新建的。

### 版本 | Version

v0.53.0

### 部署方式？ | How do you deploy vanblog?

Docker 部署(文档默认)

**Comment by Mereithhh** [comment]
你的反代有问题，被缓存了。检查你的反代配置，如果你用的宝塔，宝塔的 nginx 会自己加缓存，需要你去掉。

**Comment by lizhiqpxv** [comment]
感谢，确实有效，宝塔默认配置proxy.conf 默认缓存

**Comment by Mereithhh** [comment]
解决了就好 😃
