### ISSUE TITLE
[优化建议]: 如何部署到阿里云虚拟主机

### ISSUE THREAD

**Issue by owenzjg** [Mereithhh/vanblog#328]
### 功能概述 | Describe the feature

如上

**Comment by Mereithhh** [comment]
#3  不好意思，不支持部署到虚拟主机，原因见这个 issue

**Comment by owenzjg** [comment]
谢谢，那是否可以给我推荐一个价格在两三百的阿里云服务呢。学生党 @Mereithhh

**Comment by Mereithhh** [comment]
腾讯云活动页面 2c4g 的就够了，省着点的话 2c2g 的那个也够好像一年首次购买就100左右

**Comment by owenzjg** [comment]
这边建议安装什么系统比较适配咱们这个博客系统

**Comment by Mereithhh** [comment]
因为是 docker 安装，所以其实大差不差。 `ubuntu`, `debian` `centos` 都行。

**Comment by owenzjg** [comment]
批量操作按钮在哪里呀

**Comment by owenzjg** [comment]
我是说批量删除的

**Comment by owenzjg** [comment]
是我没有更新😭
