### ISSUE TITLE
[问题反馈]: 一键脚本更新无效？

### ISSUE THREAD

**Issue by owenzjg** [Mereithhh/vanblog#330]
### 问题描述 | Describe the bug

是否是因为我的域名还在备案，用ip访问的缘故？

实用的是一键脚本更新的

### 版本 | Version

v0.53.0

### 部署方式？ | How do you deploy vanblog?

其他方式

**Comment by Mereithhh** [comment]
能具体一点吗？ 更新的是 vanblog 吗？ 从什么版本更新的？ 更新过程中脚本输出有什么不对的地方吗？ 更新之后为啥说是无效，是版本号没变，还是无法启动了？

**Comment by owenzjg** [comment]
是vanblog
0.53.0->0.54.0
没有，就是输入一键脚本然后输入6
版本号没有变

**Comment by owenzjg** [comment]
阿哦对了，顺便问一下，不公安备案影响大吗，我看您好像就没有公安备案（还是备案了没有在末尾标记备案号）？

**Comment by Mereithhh** [comment]
> 是vanblog 0.53.0->0.54.0 没有，就是输入一键脚本然后输入6 版本号没有变

中间脚本输出了啥啊？

**Comment by Mereithhh** [comment]
> 阿哦对了，顺便问一下，不公安备案影响大吗，我看您好像就没有公安备案（还是备案了没有在末尾标记备案号）？

最好备案一下，不过不备案，如果没人找也无所谓了

**Comment by owenzjg** [comment]
等我的域名备案好了，我再试一下。现在域名没有备案好，整了服务器不好高一些东西

现在输出的东西找不到原始版本了，过两天我再发过来

感谢作者的支持，以后有自己的钱了一定打赏

**Comment by Mereithhh** [comment]
好的，你再试试，还不行的话发给我日志。 打赏倒无所谓，用的开心就好

**Comment by Mereithhh** [comment]
更新脚本有点问题，已更新，cdn 缓存同步需要一定时间，暂时的话，可以运行下面命令删除老镜像，然后再使用脚本更新即可：
```bash
docker rmi -f $(docker images | grep van-blog | awk '{print $3}')
```

**Comment by owenzjg** [comment]
@Mereithhh  感谢，网站备案已通过，可以顺便加一下博客列表吗
blog.owenzjg.com

**Comment by owenzjg** [comment]
但是输入上述指令后反馈如下

`
Error response from daemon: conflict: unable to delete 7fbff115a332 (cannot be forced) - image is being used by running container 37674e4369bd`

我是一键脚本部署的。

**Comment by Mereithhh** [comment]
那试试按照正常流程，执行一键脚本去更新？
```bash
curl -L https://vanblog.mereith.com/vanblog.sh -o vanblog.sh && chmod +x vanblog.sh && ./vanblog.sh
```

**Comment by owenzjg** [comment]
还是更新无效

过两天再试试吧，应该是cdn同步慢

**Comment by qiangzi8888** [comment]
我也是这个问题 一直脚本更新，但是版本号不变
