### ISSUE TITLE
[问题反馈]: 升级

### ISSUE THREAD

**Issue by boeai** [Mereithhh/vanblog#334]
### 问题描述 | Describe the bug

一键升级更新后，版本没变，还是当前版本，更新不到v0.54.0
<img width="404" alt="image" src="https://github.com/Mereithhh/vanblog/assets/36256586/0f026401-52ae-4f89-b04e-2ee4cf875acd">

### 版本 | Version

v0.53.0

### 部署方式？ | How do you deploy vanblog?

Docker 部署(文档默认)

**Comment by Mereithhh** [comment]
感谢反馈，更新脚本有点问题，已更新，cdn 缓存同步需要一定时间，暂时的话，可以运行下面命令删除老镜像，然后再使用脚本更新即可：
```bash
docker rmi -f $(docker images | grep van-blog | awk '{print $3}')
```

**Comment by owenzjg** [comment]
@boeai  你这个问题解决了吗？我还是更新无效
