### ISSUE TITLE
[问题反馈]: 插入Mermaid块,再次任意文本操作(包括删除文本)页面报错

### ISSUE THREAD

**Issue by XuZhuohao** [Mereithhh/vanblog#336]
## 描述
只要文章存在Mermaid块，就不能进行任何文本操作，服务器日志没有即时异常。通过chrome控制台，可以看出是md渲染后导致的（没有与后端进行交换就出现异常），不知道是否与 [bytedance#312](https://github.com/bytedance/bytemd/issues/312) 这个有关
## pc异常页面
![image](https://github.com/Mereithhh/vanblog/assets/23691075/e6057fc8-93f7-443f-ab63-39d80849a9f7)
在提供的 demo ( blog-demo.mereith.com) 测试也存在，
![image](https://github.com/Mereithhh/vanblog/assets/23691075/602254aa-3f8e-4a9c-a42f-d96e7b46896d)
## 手机异常页面
在手机端测试，写完 Mermaid 块后可以继续编辑，但是点击预览，再重新编辑一样报错
![97c5c1594ba92bc909797efefc65cdf](https://github.com/Mereithhh/vanblog/assets/23691075/e8f4f9e1-fae6-4f2d-a9c0-08b6512cd5cb)
![1cde11639e77648724695a11312cbb1](https://github.com/Mereithhh/vanblog/assets/23691075/4d3cf58b-a4cc-466d-a0f6-4900ad78f404)
这里是点了编辑，然后输入文本，就异常了
![e64cfc105896107963639c5ef8783fc](https://github.com/Mereithhh/vanblog/assets/23691075/12814446-1a84-4fc3-94dc-aa8a7a318ede)

## 附录
手机端
![97eaba4d97ad0c29fe5f4874a26a669](https://github.com/Mereithhh/vanblog/assets/23691075/d8533ffc-a1c0-4b12-8682-50e2c62195bc)
pc端
![image](https://github.com/Mereithhh/vanblog/assets/23691075/1de28109-eb70-407e-9f05-786b7b1afebb)
部署方式是通过脚本部署的，不过 demo 也是有问题，所以应该不是个别案例(为了防止是因为玄学问题导致我的浏览器影响到demo，我用平板试了下 demo，也是有问题)。我的前端有点抠脚，请大佬有空看看
对应新文章，由于我是本地写了然后复制上去，有问题也会在本地改，所以可以避过这个问题。如果是已经保存的文章存在 Mermaid 块就没法改了，只能删除文章，或者手机改(我是直接F12手机浏览模式)

### 复现网址 | Website URL

https://blog-demo.mereith.com/

### 版本 | Version

 v0.54.0

### 部署方式？ | How do you deploy vanblog?

其他方式

**Comment by Yikai-Liao** [comment]
#341 我也出现了类似报错，测试之后发现的确是mermaid的问题

**Comment by louis253** [comment]
我用不同版本的群晖部署都有这个问题，而且这个问题已经困扰很久了，至今没有解决。

**Comment by CornWorld** [comment]
@XuZhuohao 你提到的 issue 的链接已经更改为 https://github.com/pd4d10/hashmd/issues/312

**Comment by Mister-Hope** [comment]
Tracked in #341 please
