### ISSUE TITLE
不懂代码的纯纯小白跪求大佬推出广告管理模块（支持谷歌adsense），万分感谢

### ISSUE THREAD

**Issue by tomato10010** [Mereithhh/vanblog#344]
### 功能概述 | Describe the feature

> **不懂代码的纯纯小白跪求大佬推出广告管理模块（支持谷歌adsense），万分感谢** @

**Comment by 6uu1** [comment]
作者已经说过不会加广告模块了

**Comment by CornWorld** [comment]
Mereith 表示不会加入广告模块。
顺手发下群友的解决方案：https://oldmoon.top/post/96

**Comment by CornWorld** [comment]
@tomato10010 如果没什么问题了，建议关闭 Issue
