### ISSUE TITLE
[问题反馈]: 

### ISSUE THREAD

**Issue by flame1ce** [Mereithhh/vanblog#351]
### 问题描述 | Describe the bug

插入Mermaid图表， 进行内容编辑时报错：Something went wrong.Yh is not a function or its return value is not iterable，此时点击任何图标无反应，页面必须F5重新加载。

### 复现网址 | Website URL

No response

### 版本 | Version

0.54.0

### 部署方式？ | How do you deploy vanblog?

Docker 部署(文档默认)

**Comment by mMrBun** [comment]
> ### 问题描述 | Describe the bug
> 插入Mermaid图表， 进行内容编辑时报错：Something went wrong.Yh is not a function or its return value is not iterable，此时点击任何图标无反应，页面必须F5重新加载。
> 
> ### 复现网址 | Website URL
> No response
> 
> ### 版本 | Version
> 0.54.0
> 
> ### 部署方式？ | How do you deploy vanblog?
> Docker 部署(文档默认)

你好，我这边也遇到这个问题了，我看了一下前端的js代码，让chatgpt帮我改了一下报错的地方，现在已经正常使用了。
**步骤**
- 下载这个js文件 [4968.7dc2e07d.async.js](http://openwrt.mrbun.cn:5000/sharing/eyuHaIlfP)
- 如果你是docker部署的话使用下面的命令进行文件替换，如果是其他方式部署的请替换原文件就好了，该js的位置在admin目录下
```bash
docker cp 4968.7dc2e07d.async.js blog-vanblog-1:/app/admin
docker restart blog-vanblog-1
```
重启服务后记得要清除浏览器缓存
重启服务后记得要清除浏览器缓存
重启服务后记得要清除浏览器缓存
希望能帮到你。

**Comment by CornWorld** [comment]
![image](https://github.com/Mereithhh/vanblog/assets/43746030/09579c2d-6dd0-43e2-aea1-5c362f7901db)
@mMrBun

**Comment by Mister-Hope** [comment]
Duplicate of #341
