### ISSUE TITLE
[问题反馈]: 网站图标设置成功，但是页面不显示

### ISSUE THREAD

**Issue by bqey** [Mereithhh/vanblog#378]
### 问题描述 | Describe the bug

![image](https://github.com/Mereithhh/vanblog/assets/86216991/665c5ca4-2d79-4384-8817-437b4c19e603)
后台包括url都是能访问到的，
![image](https://github.com/Mereithhh/vanblog/assets/86216991/643b54b8-e838-4232-8bca-d01656f1ce33)
ye页面也正常显示url但是上面图片加载不出来
使用了NPM反代

### 复现网址 | Website URL

https://blog.fallenleave.net/link

### 版本 | Version

3

### 部署方式？ | How do you deploy vanblog?

Docker 部署(文档默认)

**Comment by bqey** [comment]
![image](https://github.com/Mereithhh/vanblog/assets/86216991/4284f31d-c162-4677-a94d-c4d7620c89a9)
z

**Comment by bqey** [comment]
解决了

**Comment by Qing1** [comment]
大哥 你这个咋解决的 遇到了类似的问题

**Comment by bqey** [comment]
当时好像在后台把图片删除，再上传选择，要不就是有缓存，清理一下，我忘了具体怎么解决了
