### ISSUE TITLE
[问题反馈]: 托管在CF的域名没法正常使用Vanblog

### ISSUE THREAD

**Issue by JIeJaitt** [Mereithhh/vanblog#415]
### 问题描述 | Describe the bug

如题，我的域名托管在cf，无论我尝试关闭CF代理还是开启CF代理，最后只能得到下图的结果：
<img width="1310" alt="image" src="https://github.com/Mereithhh/vanblog/assets/77219045/6e08a091-663b-4db7-9d7b-abe2f38150ce">

### 复现网址 | Website URL

https://jiejaitt.dedyn.io/

### 版本 | Version

截止该issue发布前最新版：[v0.54.0](https://vanblog.mereith.com/)

### 部署方式？ | How do you deploy vanblog?

一键脚本部署

**Comment by CornWorld** [comment]
此问题仍然存在吗？@JIeJaitt

**Comment by JIeJaitt** [comment]
@CornWorld 仍然存在，我怀疑是因为我用的是二级域名解析的问题，cf可能不支持二级域名解析。另外也有可能是canndy和cf的证书有冲突的语言音？总之我用了我托管在阿里云的域名之后就没问题了，托管在cf的域名是不行的

**Comment by fuweineng** [comment]
我的也托管于cf，目前一切正常。
用的是vps主机，域名a记录 ，指向IP地址/和托管都正常。
供参考
