### ISSUE TITLE
[问题反馈]: 图片无法正常显示

### ISSUE THREAD

**Issue by Qing1** [Mereithhh/vanblog#420]
### 问题描述 | Describe the bug

大佬好，部署是宝塔面板的命令行 一键部署 
然后按照 快速部署指南参考中反代的https配置  在宝塔面板的Nginx上进行配置

![Snipaste_2024-04-05_23-21-16](https://github.com/Mereithhh/vanblog/assets/13379037/6fa40205-97ca-45ef-ae1f-af0e69f123cc)

接着打开 https://blog.bxmang.top
之后出现页面作者图片无法正常显示 

![Snipaste_2024-04-05_23-08-11](https://github.com/Mereithhh/vanblog/assets/13379037/955b73a1-8ca1-48aa-9c57-dd184165aa7f)

检查页面 控制台发现是图片资源是http，
页面是https访问 导致的混合内容问题 因为 HTTPS 页面加载了 HTTP 资源 但不清楚该如何解决

![Snipaste_2024-04-05_23-17-22](https://github.com/Mereithhh/vanblog/assets/13379037/05b6373d-8b1c-4488-aa8e-e257acedccf9)
![Snipaste_2024-04-05_23-18-03](https://github.com/Mereithhh/vanblog/assets/13379037/86d7eef4-9f72-465e-93af-9cd573c97688)

后台系统设置的链接也是域名的 
不清楚具体问题该如何解决 麻烦大佬们看看

![Snipaste_2024-04-05_23-19-05](https://github.com/Mereithhh/vanblog/assets/13379037/fd138c95-0b71-4f25-bc52-7a9441a5b57f)

### 复现网址 | Website URL

https://blog.bxmang.top/

### 版本 | Version

Powered By VanBlog v0.53.0

### 部署方式？ | How do you deploy vanblog?

其他方式

**Comment by Qing1** [comment]
上述图片无法正常显示的现象是因为Nginx的缓存没有及时更新导致的  只要强制不访问缓存就可以解决了。但我对后端这些不太懂，就磕磕绊绊的按照Kimi提示修改的Nginx代码，具体的代码内容在下面链接所示。遇到这个问题的，可以做一个参考

https://daohang.bxmang.top/post/2

**Comment by xuxuxuJS** [comment]
哥们你这具体如何解决的？有步骤吗，我和你一样的情况呢

**Comment by Qing1** [comment]
> 哥们你这具体如何解决的？有步骤吗，我和你一样的情况呢

具体来说是修改nginx配置(˵¯͒〰¯͒˵)
但暂时笔记本不在身边，不方便复制我的配置给你，等晚上，有空我会贴一下，后续我会专门在我blog上写一篇文章说明下。
之前写过，但丢失了(˵¯͒〰¯͒˵)

**Comment by xuxuxuJS** [comment]
哇塞，太感谢你了，没想到你回复这么快！！！怎么联系你呀！

**Comment by Qing1** [comment]
> 哇塞，太感谢你了，没想到你回复这么快！！！怎么联系你呀！

(˵¯͒〰¯͒˵) 2148571141@qq.com，其实大家都在作者群里，里面很多大佬的😂

**Comment by Qing1** [comment]
> 哇塞，太感谢你了，没想到你回复这么快！！！怎么联系你呀！

我的对应的Nginx设置 你可以在此基础上进行修改 




 server {
    listen 80;
    server_name blog.bxmang.top; //换上你自己的网址
    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl http2;
    server_name blog.bxmang.top;//换上你自己的网址
    ssl_certificate    /www/server/blog.bxmang.top/fullchain.pem; //换上你自己的证书地址
    ssl_certificate_key    /www/server/blog.bxmang.top/privkey.pem; //换上你自己的证书key地址


    
    
    # 处理ACME挑战验证的location块 用于宝塔面板Let's Encrypt使用文件验证方法申请证书时候使用 
    location ^~ /.well-known/acme-challenge/ {
        default_type "text/plain";
        root /www/wwwroot/blog.bxmang.top/.well-known/acme-challenge; # 确保这个路径是正确的，并且包含了ACME挑战文件
        try_files $uri =404;
    }

    location / {
         # 代理设置
        proxy_pass http://127.0.0.1:8455;//换上你自己设置的端口
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header Upgrade $http_upgrade;

        # 禁用缓存的HTTP头部
        #add_header Cache-Control "no-store, no-cache, must-revalidate";
        #add_header Pragma "no-cache";
        #add_header Expires "0";

        # 清除代理缓存的设置
        proxy_cache_bypass on;
        proxy_no_cache on;
        proxy_cache_valid 0s;
        
        # 允许跨域问题
        proxy_set_header 'Access-Control-Allow-Origin' '*';
        proxy_set_header 'Access-Control-Allow-Methods' 'GET, POST, OPTIONS';
        proxy_set_header 'Access-Control-Allow-Headers' 'DNT,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Range';
    }
}

**Comment by xuxuxuJS** [comment]
不好意思，才看到，工作太忙，等我今天有空我去试试，不懂的还得请教一下你 ^  ^

**Comment by xuxuxuJS** [comment]
你的QQ网名是叫我的手机吗，我看了半天以为没搜到这个人

**Comment by xuxuxuJS** [comment]
老哥，QQ发消息给你了
