### ISSUE TITLE
🤡吃瓜贴

### ISSUE THREAD

**Issue by Mereithhh** [Mereithhh/vanblog#473]
### 问题描述 | Describe the bug

被骂了， issue 被删了，记录到这里起到警醒作用。

全部上下文：   https://joker-01.mereith.dev/

<img width="919" alt="image" src="https://github.com/user-attachments/assets/595f34ee-ffa6-41fd-9da0-263452b48fdd">
<img width="976" alt="image" src="https://github.com/user-attachments/assets/f5186331-cd03-4ff3-b9a3-d7ba2de8139f">
<img width="963" alt="image" src="https://github.com/user-attachments/assets/d990c89d-21a4-45fb-a701-dd4169059cc8">
<img width="1004" alt="image" src="https://github.com/user-attachments/assets/413e8036-f284-4440-a8a6-1b5abfd0ff41">
<img width="1022" alt="image" src="https://github.com/user-attachments/assets/1283a349-c15d-4c98-abde-db56375f59fd">

### 版本 | Version

v0.0.0

### 部署方式？ | How do you deploy vanblog?

其他方式

**Comment by Mereithhh** [comment]
<img width="610" alt="image" src="https://github.com/user-attachments/assets/24d874b5-aa2f-4449-8fa1-63789077f609">

**Comment by MichaelHao25** [comment]
这种人直接给他拉黑得了，给他梁子都拆掉，让他相当跳梁小丑都没机会，懒得搭理他。

**Comment by strangePix** [comment]
本质是其他地方受气了，没能力反抗智能找个无辜人事欺负。

**Comment by Estrella-Explore** [comment]
从 [知乎](https://www.zhihu.com/question/609374020/answer/49126987885) 过来吃瓜的 @Mereithhh 

---

您消消气，这种小丑不应该直接 close+block+pin+report+limit conversation 吗，我也遇到过这种人：

https://github.com/Estrella-Explore/gcc_strict-flags/issues/1

---

btw，已经 follow 您了

**Comment by kurisunoob** [comment]
怎么怂了，之前不是挺牛的吗

**Comment by strangePix** [comment]
> 怎么怂了，之前不是挺牛的吗

你牛你就一直牛下去，哪个正常人会和神经病纠缠到底？

**Comment by kurisunoob** [comment]
> > 怎么怂了，之前不是挺牛的吗
> 
> 你牛你就一直牛下去，哪个正常人会和神经病纠缠到底？有脾气在现实中对你上面的人发啊？跑网上对陌生人出气有一个算一个都是怂人

这种人怎么敢在现实里面横的，说不定连一个吐槽的朋友都没有

**Comment by kenvix** [comment]
![XJ$DYXC{3Y}(CVG_9EOO33](https://github.com/user-attachments/assets/02dafd02-cdf3-4d2c-bb25-e8b922a8c514)

**Comment by xmchenlx** [comment]
!!，草率了，应该留到过年看的
