### ISSUE TITLE
[优化建议]: 站点首页页面刷新时，先黑（主题）后白（主题）

### ISSUE THREAD

**Issue by aarbbs** [Mereithhh/vanblog#54]
### 功能概述 | Describe the feature

首次进入网站，或在网站首页刷新（也可以CTRL+F5），整站会先显示黑色主题（持续时间较短），然后显示为白色主题。

**Comment by aarbbs** [comment]
复现效果图：
![screenshots](https://user-images.githubusercontent.com/100953446/191292801-0ff5aa5b-9485-4548-b599-d9d281314f4c.gif)

**Comment by aarbbs** [comment]
同 Issue [https://github.com/Mereithhh/van-blog/issues/25](https://github.com/Mereithhh/van-blog/issues/25)。
下次提交问题前我先查一下重（👍）

**Comment by Mereithhh** [comment]
#25 和这个问题性质类似

因为本质上 VanBlog 是纯静态页面，首屏的时候 js 加载前，他的颜色主题是根据服务器的时间判断的。你上图中服务器时间是晚上，所以首屏就是黑色。 

等 js 加载完了，js 会读取浏览器缓存，发现你的是亮色主题模式，然后切换成亮色。就有了这次的闪屏。

如果你用自动模式，或者夜间模式就不会出现这个问题了。

我会想办法尽量缩短这个闪屏时间到肉眼不可见的地步的。

**Comment by Mereithhh** [comment]
这个 issue 先这么挂着，等我解决了再 close

**Comment by Mereithhh** [comment]
优化了一下，应该不会闪屏了，等今天发版之后就好了。 此 issue 就先关了，如果再出现再提。
