### ISSUE TITLE
[优化建议]: 编辑博客的时候，html page title 保持跟当前文章名字一致，超长的部分用 ... 代替

### ISSUE THREAD

**Issue by wujun4code** [Mereithhh/vanblog#56]
## 示例图如下

![image](https://user-images.githubusercontent.com/5119542/192122873-07edde1d-6481-4a88-8729-c73f5fee48a3.png)

因为 chrome 标签太多，分组之后，很容易找不到当前正在编辑的博客

这个是留给我自己实现的，您不需要做，我立个 flag，我尽快提交代码。

**Comment by Mereithhh** [comment]
欢迎 PR 😀  有问题请随时问我

**Comment by wujun4code** [comment]
嗯，我在家是用 windows 不方便开发前端项目，我等回公司划水摸鱼的时候用 mac 来写 😆

**Comment by Mereithhh** [comment]
刚刚改 bug 我顺手加上了（实在是没忍住，抱歉），这个 issue 就先关了哈。

感谢支持！

**Comment by wujun4code** [comment]
。。。。。。牛逼plus
