### ISSUE TITLE
[问题反馈]: 导航栏下级与副导航栏渲染图层问题

### ISSUE THREAD

**Issue by handyZYG** [Mereithhh/vanblog#60]
### 问题描述 | Describe the bug

<img width="415" alt="image" src="https://user-images.githubusercontent.com/80324720/193231860-8df8036f-cdc7-4a56-ac0e-b86430778250.png">
如图，在设置副导航栏并设置主导航栏的下级导航时，会出现图层渲染问题。

### 复现网址 | Website URL

https://www.handyzyg.cn

### 版本 | Version

v0.41.3

### 部署方式？ | How do you deploy vanblog?

Docker 部署(文档默认)

**Comment by Mereithhh** [comment]
感谢反馈，我修一下

**Comment by Mereithhh** [comment]
已修，一会发版更新一下就好了。

**Comment by handyZYG** [comment]
辛苦辛苦～～～
