### ISSUE TITLE
[问题反馈]: md编辑器在混用html后（尤其数学公式后）造成的缩进问题

### ISSUE THREAD

**Issue by handyZYG** [Mereithhh/vanblog#62]
### 问题描述 | Describe the bug

<img width="1680" alt="image" src="https://user-images.githubusercontent.com/80324720/193298464-45779929-4ac7-4f70-98d9-870cb0ef972d.png">
<img width="1680" alt="image" src="https://user-images.githubusercontent.com/80324720/193298493-0f5471c7-12eb-4324-bf1f-a7911fd2de3b.png">
如图，在混用html做合并单元格的表格后，后台预览没问题，但前端显示出现缩进问题。

### 复现网址 | Website URL

https://www.handyzyg.cn/post/33

### 版本 | Version

0.41.3

### 部署方式？ | How do you deploy vanblog?

Docker 部署(文档默认)

**Comment by Mereithhh** [comment]
感谢反馈，我处理一下。不过明天要回老家过节，这两天可能改不完，不过我尽快。

**Comment by handyZYG** [comment]
辛苦大佬！

**Comment by Mereithhh** [comment]
## 进展

提问者和我说了解决办法，把 table 标签对齐就好了 （如果我的理解没错）。此 issue 就先关了
![{59C6D674-5897-77C1-0F37-89DBEE4B8AFF}](https://user-images.githubusercontent.com/22872368/194459602-e3c8a30c-00b0-4119-bb59-4542fae3b241.jpg)

![image](https://user-images.githubusercontent.com/22872368/194459663-c0629968-7224-4d26-b6b5-d96ff502e5a5.png)
