### ISSUE TITLE
[优化建议]: 网站底部公安备案展示

### ISSUE THREAD

**Issue by sundongyu** [Mereithhh/vanblog#65]
### 功能概述 | Describe the feature

建议在网站底部可支持添加公安备案信息的添加，包括备案图标及备案号

**Comment by Mereithhh** [comment]
收到，我安排一下

**Comment by Mereithhh** [comment]
已修改，今天发版之后就好了。 commit 忘了关联了 ：[9a43d7f4582a35a6962a97871df3972ff2f46c74](https://github.com/Mereithhh/vanblog/commit/9a43d7f4582a35a6962a97871df3972ff2f46c74)
