### ISSUE TITLE
[问题反馈]: 目前发现博客内部，除了网址图标和MD图片引用外，其他的位置如果使用外部图床，图片无法显示

### ISSUE THREAD

**Issue by SmallOrangeGame** [Mereithhh/vanblog#67]
### 问题描述 | Describe the bug
![image](https://user-images.githubusercontent.com/58835407/195004899-99b265ef-ef73-4b3c-b12c-25376960bc91.png)

图床设置为腾讯COS，结果导入的图片无法显示
https://pic.xiaojuziya.com/picgo/logo.png
例如这张
![image](https://user-images.githubusercontent.com/58835407/195004509-11be8a5f-d9f4-4073-93bc-9deb0b264b3a.png)
网址图片链接不对
![image](https://user-images.githubusercontent.com/58835407/195004666-2e548a6d-3df5-449d-91f7-f2b06d31bb8a.png)

### 复现网址 | Website URL

https://www.xiaojuziya.com/

### 版本 | Version

v0.41.5

### 部署方式？ | How do you deploy vanblog?

Docker 部署(文档默认)

**Comment by SmallOrangeGame** [comment]
picgo配置是从本地picgo拷贝过去的
{
  "picBed": {
    "current": "tcyun",
    "uploader": "tcyun",
    "smms": {
      "token": ""
    },
    "tcyun": {
      "version": "v5",
      "secretId": "***",
      "secretKey": "***",
      "bucket": "***",
      "appId": "***",
      "area": "ap-chengdu",
      "path": "picgo/",
      "customUrl": "https://pic.xiaojuziya.com",
      "options": ""
    },
    "list": [
      {
        "type": "tcyun",
        "name": "腾讯云COS",
        "visible": true
      }
    ]
  },
  "settings": {
    "shortKey": {
      "picgo:upload": {
        "enable": true,
        "key": "CommandOrControl+Shift+P",
        "name": "upload",
        "label": "QUICK_UPLOAD"
      }
    },
    "showUpdateTip": true,
    "server": {
      "port": 36677,
      "host": "127.0.0.1",
      "enable": true
    },
    "pasteStyle": "HTML",
    "privacyEnsure": true,
    "autoStart": true,
    "useBuiltinClipboard": true,
    "rename": true,
    "autoRename": true
  },
  "needReload": false,
  "picgoPlugins": {},
  "debug": true,
  "PICGO_ENV": "GUI"
}

**Comment by Mereithhh** [comment]
你检查一下部署 vanblog 时的 "ALLOW_DOMAINS" 变量，多半是因为这个没加上你的图床域名。

**Comment by Mereithhh** [comment]
你把 `pic.xiaojuziya.com` 加上去试试，注意用英文逗号分隔。  如果是一键脚本部署，执行修改配置。如果是 `docker-compose` 部署，那就改一下编排里的环境变量再重启即可。 
![image](https://user-images.githubusercontent.com/22872368/195112068-0726f688-7a6f-4422-bd4d-8c3626542b6a.png)

**Comment by Mereithhh** [comment]
在交流群里反馈来看，应该已经解决了，此 issue 就先关了
