### ISSUE TITLE
[问题反馈]: 域名访问不显示新增文章，ip访问可以

### ISSUE THREAD

**Issue by yo2yoake** [Mereithhh/vanblog#69]
### 问题描述 | Describe the bug

部署方式：docekr-compose

docker-compose.yml文件改动：仅将端口映射改为了28080:80以及28443:443，因为80端口被nginx占用

反代情况：宝塔面板nginx，将域名反代到了28080端口(http协议)，域名已经绑定了SSL证书

情景描述：
我在域名访问中新建了一篇测试文章，该文章未隐藏，返回主页想查看的时候发现并未更新这篇文章，更换设备再次查看依然如此，遂排除是浏览器缓存的问题。使用ip:端口访问，发现文章已经正常更新至主页。
![5BX(BE{1{QAOS7NBT3{FFEU](https://user-images.githubusercontent.com/88564661/195335921-905b7729-acbe-4242-b88b-c7dbecb50f74.png)
![U`PJIDZEO3F(9)LQI83H@94](https://user-images.githubusercontent.com/88564661/195335922-c191089b-6585-40a2-8368-3eb4e3f9e480.png)

细节补充：
1. 两种访问方式下，页面底部的浏览量都是正常更新的
2. 在域名访问下，可以在后台中看到测试文章的数据![VQ8((DC 18G`{CM L)Q%6P](https://user-images.githubusercontent.com/88564661/195337708-8e705335-7227-48be-9078-aae08a4fbbc6.png)
3. 根据issues#50的描述检查，确认自己未配置CDN

以上就是我遇到的问题，新人刚接触不久，有什么错误希望您指导一下

### 版本 | Version

v0.41.5

### 部署方式？ | How do you deploy vanblog?

Docker 部署(文档默认)

**Comment by yo2yoake** [comment]
已解决，原因是nginx配置文件有错误未发现

**Comment by yo2yoake** [comment]
nginx的配置文件（部分信息做了隐藏）
server {
  listen 80;
  server_name <域名>;
  return 301 https://$host$request_uri;

}
server {
  listen 443 ssl http2;
  server_name <域名>;
  # 证书的公私钥
    ssl_certificate    <路径>;
    ssl_certificate_key    <路径>;

  location / {
    # 改为容器的 PORT
    proxy_pass http://127.0.0.1:28080;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_set_header Upgrade $http_upgrade;
  }

**Comment by Mereithhh** [comment]
之前有朋友也和我反馈了类似的问题。 经过排查是因为宝塔 nginx 本身的问题，他卸载了宝塔自带的 nginx ，然后手动安装了新版 nginx（通过系统的包管理器）后，解决了此问题。

您也这样试试看？看现象应该就是反代的问题。 如果还是不能解决，您可以加我微信，我帮您排查一下。

PS: 我怀疑宝塔 nginx 本身会在您自定义的配置文件外自动添加一些配置，或者是有一些专门为了宝塔面板做的客制化改造，导致了这个问题。

**Comment by Mereithhh** [comment]
问题解决了吗？@yo2yoake

**Comment by Wrm244** [comment]
我现在也是出现了这个问题
后台更新了文章，但主页不更新，删掉了还显示
![image](https://user-images.githubusercontent.com/54385511/207236422-771a4c69-a2be-4e60-9db0-f2cd6ec0f66f.png)
复现网址 | Website URL
speed.ist4102.cloud

版本 | Version
v0.43.1

部署方式？ | How do you deploy vanblog?
脚本部署

**Comment by Mereithhh** [comment]
@Wrm244 这个一般是宝塔 nginx 的问题，你卸载了宝塔自带的 nginx，手动装一个新版就好了。

**Comment by Mereithhh** [comment]
目前我遇到有问题的基本都是这样子

**Comment by Mereithhh** [comment]
如果一台服务器只是部署 vanblog，我不推荐用宝塔。 直接 ssh 连进去跑一个一键脚本就好了。 或者把宝塔的 nginx 删了，用 `nginx-proxy-manager` 作为反代会更好用。

**Comment by Wrm244** [comment]
我加了这一段配置可以解决：
```
location /
{
    proxy_pass http://127.0.0.1:8090;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header REMOTE-HOST $remote_addr;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection $connection_upgrade;
    proxy_http_version 1.1;
    # proxy_hide_header Upgrade;

    add_header X-Cache $upstream_cache_status;
		#Set Nginx Cache

    proxy_set_header Accept-Encoding "";
		sub_filter "http://localhost:8090" "$host";
		sub_filter "localhost:8090" "$host";
    sub_filter_once off;

    if ( $uri ~* "\.(gif|png|jpg|woff|woff2)$" )
    {
        expires 1s;
    }
    proxy_ignore_headers Set-Cookie Cache-Control expires;
    proxy_cache cache_one;
    proxy_cache_key $host$uri$is_args$args;
    proxy_cache_valid 200 304 301 302 0m;
}
```

**Comment by Mereithhh** [comment]
可以的，我回头加到文档中，谢谢提醒
