### ISSUE TITLE
[优化建议]: 代码块样式

### ISSUE THREAD

**Issue by sundongyu** [Mereithhh/vanblog#71]
### 功能概述 | Describe the feature

建议在代码块右上角或者其他地方显示当前代码块的语言类型
类似于这种：
![image](https://user-images.githubusercontent.com/56066397/196092730-a891c11e-ceab-4af6-a033-7d13ac78661f.png)

**Comment by Mereithhh** [comment]
收到

**Comment by Mereithhh** [comment]
已修改，今天发版之后就好了。
