### ISSUE TITLE
[问题反馈]: 代码块显示异常

### ISSUE THREAD

**Issue by sundongyu** [Mereithhh/vanblog#72]
### 问题描述 | Describe the bug

当一行代码刚好占满一行的时候，最后一个字母会被复制按钮挡住
![image](https://user-images.githubusercontent.com/56066397/196322022-ef6709ea-1912-4222-bd4f-1476f5874e72.png)

### 复现网址 | Website URL

https://wetf.top/post/2

### 版本 | Version

v0.41.5

### 部署方式？ | How do you deploy vanblog?

Docker 部署(文档默认)

**Comment by Mereithhh** [comment]
收到，我处理一下

**Comment by sundongyu** [comment]
vanblog项目文档的代码块样式就挺好的
![image](https://user-images.githubusercontent.com/56066397/196450427-e219e780-b343-481a-9254-27b0e7cdb454.png)

**Comment by Mereithhh** [comment]
我看看哈，目前我个人还是觉得复制按钮在右上角会舒服一点，因为代码很长的话就不用往下翻了。我先把遮挡问题处理一下。

**Comment by sundongyu** [comment]
对，复制按钮在右上比较好
________________________________

**Comment by Mereithhh** [comment]
已修改，今天发版之后就好了。
