### ISSUE TITLE
[优化建议]: 代码块显示

### ISSUE THREAD

**Issue by sundongyu** [Mereithhh/vanblog#73]
### 功能概述 | Describe the feature

代码块横向滚动条过于粗大
![image](https://user-images.githubusercontent.com/56066397/196325123-f985e9d6-59b2-477f-9b89-ce25f46063b7.png)
建议参照这种大小
![image](https://user-images.githubusercontent.com/56066397/196325287-4da72ec5-6d3b-4824-9769-0daf8d14d32b.png)

**Comment by Mereithhh** [comment]
好的，我调整一下

**Comment by Mereithhh** [comment]
已修改，今天发版之后就好了。

**Comment by JIeJaitt** [comment]
现在代码块没有横向滚动条了？
