### ISSUE TITLE
[问题反馈]: 关于文档

### ISSUE THREAD

**Issue by CornWorld** [Mereithhh/vanblog#76]
### 问题描述 | Describe the bug

1. 无法使用`编辑此页`按钮
2. 有一处拼写错误，`and design pro` 应该改为 `ant design pro`

### 复现网址 | Website URL

https://vanblog.mereith.com/ref/dev.html#%E6%8A%80%E6%9C%AF%E6%A0%88

### 版本 | Version

Current

### 部署方式？ | How do you deploy vanblog?

其他方式

**Comment by CornWorld** [comment]
#77 已经提交 PR

**Comment by CornWorld** [comment]
点击`编辑此页`跳转到的位置：`Mereithhh/vanblog/edit/main/demo/src/ref/dev.md`
实际上的位置：`Mereithhh/vanblog/edit/master/docs/ref/dev.md`

**Comment by Mereithhh** [comment]
感谢反馈，我处理一下

**Comment by Mereithhh** [comment]
已经处理，感谢支持！
