### ISSUE TITLE
[问题反馈]: 换行显示异常

### ISSUE THREAD

**Issue by hxcaihm** [Mereithhh/vanblog#78]
### 问题描述 | Describe the bug

在文章编辑器中换行可以正常显示：
![image](https://user-images.githubusercontent.com/66231422/198803015-8e53c082-2c4b-45e9-a284-305710154377.png)
![image](https://user-images.githubusercontent.com/66231422/198803123-15923dff-874a-4482-9144-42b127b5948b.png)
而在发布后的文章浏览界面不会换行：
![image](https://user-images.githubusercontent.com/66231422/198803955-5e76b107-a30f-4210-ac0f-98580343932f.png)

### 版本 | Version

v0.42.0

### 部署方式？ | How do you deploy vanblog?

Docker 部署(文档默认)

**Comment by Mereithhh** [comment]
收到，我处理一下

**Comment by Mereithhh** [comment]
修了，一会发版后更新就好了。
