### ISSUE TITLE
[问题反馈]: 【备份和恢复】恢复后文章 post 后面数字的顺序与原来相反

### ISSUE THREAD

**Issue by immengzi** [Mereithhh/vanblog#80]
## 迁移前最新文章

![image](https://user-images.githubusercontent.com/95157017/200293068-e5c2d41c-302a-43f8-92ca-1145ea748851.png)

## 迁移后最新文章

![image](https://user-images.githubusercontent.com/95157017/200292908-7a50a5f5-39da-43de-ae8e-99ed986296b0.png)

### 版本 | Version

最新

### 部署方式？ | How do you deploy vanblog?

Docker 部署(文档默认)

**Comment by Mereithhh** [comment]
收到，我处理一下
