### ISSUE TITLE
[优化建议]: 希望联系方式中添加gitee配置

### ISSUE THREAD

**Issue by Dozingfiretruck** [Mereithhh/vanblog#81]
### 功能概述 | Describe the feature

希望联系方式中添加gitee配置
![image](https://user-images.githubusercontent.com/24759100/200355319-fa92c120-281c-4c9d-9328-0429c902bedc.png)

**Comment by Mereithhh** [comment]
收到

**Comment by Mereithhh** [comment]
加上了，发版的时候就带上去。
