### ISSUE TITLE
[问题反馈]: 未知原因导致 Inode 空间和磁盘空间大量占用

### ISSUE THREAD

**Issue by CornWorld** [Mereithhh/vanblog#85]
### 问题描述 | Describe the bug

> 本 Issue 转述自 QQ 群， 本人未遇到此问题

#### 2889227439 （Docker、磁盘空间大量占用）
> 上次磁盘满了,然后docker挂掉了,过了10天,现在又满了,可是我没有很多文章在上面
> (是)手动部署的
> 这个月10号部署的,然后每时每刻都在写文件,到现在写满了
> vanblog容器占用的空间, 我正在删除容器, 硬盘就有空间了
> 版本是0.42
> ![2% XQ@V4{)II%V_3L5HU){M](https://user-images.githubusercontent.com/43746030/202332381-be15300e-3177-4ada-8666-c9a9d18bcfbf.png)
> ![J J1D`$RU5_C}6VLTM5%UVU](https://user-images.githubusercontent.com/43746030/202332408-5e2d3e26-4017-465f-aa84-3798dfee8d83.jpg)

#### 1647562864 (shell script、磁盘空间大量占用)
> 我都没怎么动，咋生产了这么多东西？都是日志吗？
> ![%E4}ROP9S}@6(SD 0YF26H6](https://user-images.githubusercontent.com/43746030/202332822-293505e2-6825-4bf0-8c12-73cb1cc0ed38.jpg)
> 它那个内存(此处指的是储存)会一直自己涨
> 就用的一键部署
> 尽管你啥都没做

#### 1686769963 （shell script、Inode 空间大量占用）
> 我的博客系统昨天炸了
> 原因是 inode 满了

>

### 复现网址 | Website URL

Undefined

### 版本 | Version

v0.42

### 部署方式？ | How do you deploy vanblog?

其他方式

**Comment by CornWorld** [comment]
经检查，此 Issue 疑似由 yarn 造成，行为与 https://github.com/yarnpkg/yarn/issues/6685 完全一致。

**Comment by CornWorld** [comment]
有位群友的 v0.41.5 未出现此问题，目前对上述处理(#92)存疑.

**Comment by Mereithhh** [comment]
收到，我排查一下，前两天一直在搬家。。

**Comment by CornWorld** [comment]
#93 与此问题为同一问题

**Comment by Mereithhh** [comment]
查明原因是因为 server 内置 child_process 管理 website 服务时，重启逻辑存在死循环的情况，每次重启都会生成一些缓存文件，大量不间断的的死循环重启就会导致占满 inode 和磁盘空间。

**Comment by Mereithhh** [comment]
修了一下，正在发布，在 `v0.43.1` 这个新版本中会得到解决。 这个 bug 的影响范围是 `v0.42.0` 到 `v0.43.0`，此 issue 就先关闭了，收到更新提示更新一下就好了。
