### ISSUE TITLE
[问题反馈]: 目录自动回到顶部

### ISSUE THREAD

**Issue by sundongyu** [Mereithhh/vanblog#87]
### 功能概述 | Describe the feature

当通过右侧文章目录选择一个标题后，点击标题，文章跳转到相应位置，此时目录应该位于当前文章对应的标题处，然而无论点击哪个标题，点击过后，目录就会回到最顶部
![image](https://user-images.githubusercontent.com/56066397/202365670-889a7059-d506-47e8-8f09-9d5b6061c2af.png)

**Comment by Mereithhh** [comment]
收到

**Comment by Mereithhh** [comment]
修了，这是我整个前端生涯遇到最离奇的 bug 了。
